
---
- name: "Locate running process for {{ oracle_db.service_name }}"
  environment:
    ORACLE_DB: "{{ oracle_db.service_name }}"
  shell: |
    ps aux | grep pmon | grep -v grep | grep "$ORACLE_DB" | awk '{print $1}'
  register: oracle_db_sid_owner

- name: "No running database named {{ oracle_db.service_name }} was found"
  debug:
    msg: |
      "Running database process was not found for {{oracle_db.service_name}}.  Skipping deployment"
  when:
    - "(oracle_db_sid_owner.rc is defined and oracle_db_sid_owner.rc > 0) or (oracle_db_sid_owner.stdout is defined and oracle_db_sid_owner.stdout == '')"

- name: Database found.  Proceeding to deploy instance caging and resource manager plan
  block:
    - name: "Set DB owner for {{ oracle_db.service_name }}"
      set_fact:
        oracle_db_owner: "{{oracle_db_sid_owner.stdout}}"
    - name: "Set resource_manager_plan & allocated cores for {{ oracle_db.service_name }}"
      environment:
        ORACLE_DB: "{{oracle_db.service_name}}"
        ORAENV_ASK: "NO"
      shell: |
        export PATH=/usr/local/bin:$PATH
        export ORACLE_SID=$(cat /etc/oratab | grep -v "^#" | grep -v "N$" | grep "$ORACLE_DB" | head -1 | cut -f1 -d: -s)
        export ORACLE_HOME=$(cat /etc/oratab | grep -v "^#" | grep -v "N$" | grep "$ORACLE_DB" | head -1 | cut -f2 -d: -s)
        export ORACLE_SID=$(ps -e -o command | grep pmon | grep -v grep | cut -d '_' -f3 | grep "$ORACLE_DB"  | head -1)
        . /usr/local/bin/oraenv
        $ORACLE_HOME/bin/sqlplus -s "/ as sysdba" <<SQLPLUS
        /bin/sqlplus -s "/ as sysdba" <<SQLPLUS
          alter system set resource_manager_plan = {{oracle_db.resource_manager_plan}} SID='*' scope=both;
          alter system set cpu_count = {{oracle_db.allocated_cores}};
          exit
        SQLPLUS
      register: sqlplus_db_cage
      become: yes
      become_user: "{{oracle_db_owner}}"
      failed_when:
        - "((sqlplus_db_cage.rc is defined and sqlplus_db_cage.rc == 0 and 'ORA-' in sqlplus_db_cage.stdout) or (sqlplus_db_cage.rc is defined and sqlplus_db_cage.rc > 0))"
      run_once: yes
      ignore_errors: yes
  when:
    - "oracle_db_sid_owner.rc is defined"
    - "oracle_db_sid_owner.rc == 0"
    - "oracle_db_sid_owner.stdout is defined"
    - "oracle_db_sid_owner.stdout != ''"
